### ISSUE TITLE
names modified: string b

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/Alegreya#8]
In the names modified table string_b references a Regular instead of Black.   Which column are we reviewing _a or _b?   
I am accepting the pull request because in the RF UFOs the names appear as expected.

![Diff roman Black 2019-11-20 at 1 49 32 PM](https://user-images.githubusercontent.com/6576107/69271653-3d0c1c00-0ba3-11ea-9e70-3e865cd7a0bf.png)

![Diff roman ufo names](https://user-images.githubusercontent.com/6576107/69271661-41383980-0ba3-11ea-9577-edd80623ecce.png)

**Comment by cjdunn** [comment]
@pichotta I'm not sure about these differences. I also can see that they look good in the UFO masters, so hopefully they're OK as is. 

@m4rc1e please let us know if these need to be changed, otherwise we'll leave as is, thanks

**Comment by m4rc1e** [comment]
Family looks good to me aka LGTM.
